server:
  port: 8761
  version: 1.0.0
spring:
  datasource:
    name: test
    url: jdbc:mysql://nc.hyt.com:3306/test
    username: root
    password: 111111
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  application:
    name: ${artifactId}
  # Redis
  redis:
    host: 127.0.0.1
  servlet:
    multipart:
      # 默认最大上传文件大小为1M，单个文件大小
      max-file-size: 50MB
      # 默认最大请求大小为10M，总上传的数据大小
      max-request-size: 500MB
      # 默认支持文件上传
      enabled: true
      # 支持文件写入磁盘
      file-size-threshold: 0



mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.cntest.su.demo.entity


#定时任务
scheduled:
  cron: 0/5 * * * * ?
enable:
  scheduled: false


remote-algorithm:
  ip: 172.0.0.1
  port: 2233
  username: root
  password: static/algorithem
  path: /home/MarketSimulate
  command: ./py36/bin/python -W ignore ProcessTest.py

# 分布式文件系统FastDFS配置
fdfs:
  # 读取时间
  so-timeout: 1501
  # 连接超时时间
  connect-timeout: 601
  # 缩略图生成参数
  thumb-image:
    width: 150
    height: 150
  # 前端访问url
  webServerUrl: http://176.16.1.21:50008/
  # Tracker服务，支持多个
  tracker-list:
    - 176.16.1.21:50009